### ISSUE TITLE
export to touchdesigner

### ISSUE THREAD

**Issue by PWhiddy** [shader-park/shader-park-core#19]

**Comment by torinmb** [comment]
This is close. Right now I'm just exporting the surfaceDistance and shade function and pasting it in my existing .tox file.
I just need to export the core library and change the name of main function and download it as a .glsl
I should also upload my .tox file with a .readme on how to swap out the shader code.

**Comment by PWhiddy** [comment]
Ok. To be clear, for this to be complete it needs a TD target in sp-core that provides an api that goes from a sculpt string directly to a string/file(s) that can be opened in TD without any extra manual steps. The point is that these export targets need to work completely from the API so that you could easily integrate SP into the target for live coding. To be clear, 0% of this conversion should be implemented in the website's repo

**Comment by torinmb** [comment]
something like this? https://github.com/bnanner/sculpture-park-core/commit/e9655cc9f9bb878c98a9c080ac9472cfe94ecb7e

**Comment by torinmb** [comment]
The .tox file isn't included. You have to open the ShaderPark.tox file, open one of the nodes and paste in the generated code

**Comment by PWhiddy** [comment]
What would it take to avoid having to copy paste?

**Comment by torinmb** [comment]
I could potentially set it up so the TD project imports the glsl content from an external file. That way you could drop a new file in, or if you’re using sp-core locally you could have your saved changes overwrite the file. Makes me want to have a VS code plugin for the library

**Comment by PWhiddy** [comment]
Hm interesting. It would be super cool if were able to find a way to integrate it with unity/TD that lets you edit the sculpt file and have the changes automatically generate and load in the application. Would require making a plugin/script to run in unity/TD, but probably not actually too difficult and would be a huge leap for the scope of the project

**Comment by PWhiddy** [comment]
Automatically regenerating a glsl/hlsl file needed in unity/TD would be easy. thats just a program that watches for changes in the file your editing and then automatically runs sp-core to a target file. We then just need that script to talk to unity/TD (they both have nice APIs) to tell them to reload/recompile the shader. Pretty straightforward I think actually. A solid stretch goal at least.

**Comment by torinmb** [comment]
https://github.com/shader-park/shader-park-touchdesigner. we did it
