### ISSUE TITLE
example using sp at build time

### ISSUE THREAD

**Issue by PWhiddy** [shader-park/shader-park-core#87]
making the shipped product much lighter and less compute heavy. 
only appropriate for situations where code doesn’t change after page is loaded, but this is probably the common case anyway

**Comment by torinmb** [comment]
[babel code gen](https://youtu.be/1queadQ0048?t=208) is a great reference. Also, [glslify](https://github.com/glslify/glslify)

**Comment by torinmb** [comment]
working example: https://github.com/shader-park/shader-park-examples/tree/main/es6-production-template
